### ISSUE TITLE
TEXT VID DATASET AND MODEL CHECKPOINT

### ISSUE THREAD

**Issue by Divyanshupy** [dhg-wei/TOPA#2]
Dear Team, 

Thank you for the amazing work. I was wondering if it was possible to release the dataset and the model checkpoints for the TOPA paper.

Thank you again for the amazing work.

**Comment by WangWenhao0716** [comment]
+1

**Comment by WangWenhao0716** [comment]
Also, an inference demo is expected. For example, something like this one is good: https://github.com/WangWenhao0716/AnyPatternStyle

**Comment by dhg-wei** [comment]
Thank you for your interest in our work! The data and checkpoints are released~

**Comment by WangWenhao0716** [comment]
Thanks for authors' reply. Congrats for being accepted as Spotlight in NeurIPS 2024

**Comment by Divyanshupy** [comment]
Thank you so much and congratulations.

**Comment by Divyanshupy** [comment]
Hey, first of all, the code is very well-written and easy to follow. I have a request, will it be possible to share the text_vid dataset clip features and memory features you use for training/evaluating the model? 
Thank you again.

**Comment by dhg-wei** [comment]
@Divyanshupy Updated!

**Comment by Divyanshupy** [comment]
Amazing work and thank you for the help. I am closing the issue now.
